# Generated by Django 4.2 on 2023-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
