# Generated by Django 4.2 on 2023-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='first_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
