# Generated by Django 4.2 on 2023-04-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_writer_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.writer'),
        ),
    ]
