# Generated by Django 4.2 on 2023-04-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.writer'),
        ),
        migrations.CreateModel(
            name='FavBookCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='book.book')),
            ],
        ),
    ]
