# Generated by Django 4.2 on 2023-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_cerated_book_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
